language: node_js
node_js:
  - "7"

cache:
  directories:
    - node_modules

install: npm install

script:
  - npm run test:coverage
  - echo $CODECLIMATE_TOKEN
  - codecov --token=$CODECLIMATE_TOKEN
